# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: '3'
services:
  jenkins:
    user: root
    image: jenkinsci/blueocean
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkinsci
    ports:
      - "8080:8080"
      - "50000:50000"